terraformer:
  nameOverride: "bc-wallet-common-trrfrm-worker"

  serviceAccount:
    worker:
      create: true
      annotations: {}
      name: "cryptobundle-bc-wallet-common-trrfrm-worker"

  vault:
    agent:
      inject_secret_path: 'kv/data/crypto-bundle/bc-wallet-common/trrfrm/worker'

      inject_template: |
        {{- with secret "kv/data/crypto-bundle/bc-wallet-common/trrfrm/worker" -}}
        PGPASSWORD="{{ .Data.data.POSTGRESQL_PASSWORD }}"
        PGUSER="{{ .Data.data.POSTGRESQL_USERNAME }}"
        {{- end -}}

      role:
        _default: cryptobundle-bc-wallet-common-trrfrm-worker

  dataStorage:
    enable: true
    mountPath: "/vault/data"

  jobAnnotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded

  cli_arguments:
    - name: "k8s_namespace"
      value: "{{ .Release.Namespace }}"