# PARENT_CONTAINER_IMAGE_NAME - base trrfrm container
ARG PARENT_CONTAINER_IMAGE_NAME

FROM $PARENT_CONTAINER_IMAGE_NAME

ARG TRFRM_SOURCE_DIR="/opt/trrfrm/source"

COPY deploy/trrfrm/init $TRFRM_SOURCE_DIR
