# PARENT_CONTAINER_IMAGE_NAME - base trrfrm container
ARG PARENT_CONTAINER_IMAGE_NAME

FROM $PARENT_CONTAINER_IMAGE_NAME

ARG TRFRM_SOURCE_DIR="/opt/trrfrm/source"
ARG TRFRM_PROJECT_NAME="bc-wallet-common-trrfrm"
ENV TRFRM_PROJECT_NAME=$TRFRM_PROJECT_NAME
#ENV TRFRM_DATA_DIR=$TF_DATA_DIR
#ENV TRFRM_WORK_DIR=$TRFRM_WORK_DIR
#ENV TF_DATA_DIR="$TRFRM_WORK_DIR/.terraform"

COPY deploy/trrfrm/init $TRFRM_SOURCE_DIR

RUN apk --update add postgresql-client
