{{/*
Copyright (c) 2024 Aleksei Kotelnikov(gudron2s@gmail.com)
License: MIT NON-AI
*/}}

{{- define "bc-wallet-common-trrfrmr.job.tpl" -}}
{{- $randTmpDirPostfix := randAlphaNum 9 | nospace -}}
{{- $data := dict "Values" .Values "Chart" .Chart "TmpDirPostfix" $randTmpDirPostfix -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.terraformer.jobAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ include "app.name" . }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
      annotations:
      {{- with .Values.terraformer.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        {{- include "_vault_agent_annotations" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.terraformer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "app.name" . }}-tmp-dir
          emptyDir: {}
        - name: {{ include "pv.prefix" . }}-providers-pv-storage
          persistentVolumeClaim:
            claimName: {{ include "pv.prefix" . }}-providers-pv-claim
      {{- with .Values.terraformer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.terraformer.serviceAccount.name | quote }}
      initContainers:
{{/*        {{- include "subchart.init.containers" . | nindent 8 }}*/}}
        - name: {{ include "app.name" . }}-init
          image: {{ .Values.terraformer.image.path }}:{{ .Values.terraformer.image.tag }}
          imagePullPolicy: {{ .Values.terraformer.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.terraformer.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.terraformer.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "app.name" . }}-tmp-dir
              mountPath: /tmp
            - name: {{ include "pv.prefix" . }}-providers-pv-storage
              mountPath: {{ pluck .Values.global.env .Values.terraformer.terrraformDirectory.work | first | default .Values.terraformer.terrraformDirectory.work._default | quote }}
          env:
            {{- include "_env_app_terraform" $data | nindent 12 }}
          args:
            - "init"
          {{- range $key, $argument := .Values.terraformer.cli_arguments }}
            - "-var={{ $argument.name }}='{{ tpl $argument.value $ }}'"
          {{- end }}

      containers:
        - name: {{ include "app.name" . }}-apply
          image: {{ .Values.terraformer.image.path }}:{{ .Values.terraformer.image.tag }}
          imagePullPolicy: {{ .Values.terraformer.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.terraformer.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.terraformer.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "app.name" . }}-tmp-dir
              mountPath: /tmp
            - name: {{ include "pv.prefix" . }}-providers-pv-storage
              mountPath: {{ pluck .Values.global.env .Values.terraformer.terrraformDirectory.work | first | default .Values.terraformer.terrraformDirectory.work._default | quote }}
          env:
            {{- include "_env_app_terraform" $data | nindent 12 }}
          args:
            - "apply"
            - "-auto-approve"
          {{- range $key, $argument := .Values.terraformer.cli_arguments }}
            - "-var={{ $argument.name }}={{ tpl $argument.value $ }}"
          {{- end }}
{{- end -}}