# Copyright (c) 2024 Aleksei Kotelnikov(gudron2s@gmail.com)
# License: MIT NON-AI

imports: {}

terraformer:
  replicaCount: 1

  resources:
    limits:
      cpu: 2500m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 96Mi

  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

  nameOverride: "bc-wallet-common-trrfrm"
  fullnameOverride: ""

  serviceAccount:
    create: true
    annotations: {}
    name: "cryptobundle-bc-wallet-common-trrfrm-worker"

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  imagePullSecrets: []

  jobAnnotations: {}

  podAnnotations: {}

  terrraformDirectory:
    source_code:
      _default: /opt/trrfrm/source

    work:
      _default: /opt/trrfrm/work

    cache:
      _default: /opt/trrfrm/work/.terraform.d/plugin-cache


  providersStorage:
    enabled: true
    size: 2Gi
    storageClass: openebs-hostpath
    accessMode: ReadWriteOnce
    annotations: {}

  hook:
    enabled: false
    weight: -5

  db:
    host:
      _default: "postgresql.default.svc.cluster.local"
    port:
      _default: 5432

    ssl_mode:
      _default: disable

    name:
      _default: bc-wallet-common-trrfrm

    schema:
      _default: bc-wallet-common-trrfrm

  env:
    file_name:
      _default: /vault/secrets/env

  vault:
    host:
      _default: "vault.default.svc.cluster.local"
    port:
      _default: 8200
    use_https:
      _default: false

    agent:
      inject:
        _default: true

      role:
        _default: cryptobundle-bc-wallet-common-trrfrm-worker

      inject_perms:
        _default: 664

      inject_token:
        _default: true

      inject_secret_path: 'kv/data/crypto-bundle/bc-wallet-common/trrfrm/init'

      inject_template: |
        {{- with secret "kv/data/crypto-bundle/bc-wallet-common/trrfrm/init" -}}
        PGPASSWORD="{{ .Data.data.POSTGRESQL_PASSWORD }}"
        PGUSER="{{ .Data.data.POSTGRESQL_USERNAME }}"
        {{- end -}}

      init_first:
        _default: true

      pre_populate:
        _default: true

    token_path:
      _default: /vault/secrets/token

  cli_arguments:
    - name: "k8s_namespace"
      value: "{{ .Release.Namespace }}"

  image:
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    path: repository.local/crypto-bundle/bc-wallet-common-hdwallet-trrfrmr
    tag: latest